# Generated by Django 3.2.7 on 2021-10-03 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20211003_1203'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Skil',
            new_name='Skill',
        ),
    ]
