# Generated by Django 3.2.8 on 2021-10-10 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['created_at', 'name']},
        ),
    ]
