# Generated by Django 3.2.7 on 2022-04-16 01:15

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_profile_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(blank=True, default='profiles/user-default.png', max_length=255, null=True),
        ),
    ]
