# Generated by Django 3.2.7 on 2022-04-16 01:15

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_alter_project_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(blank=True, default='default.jpg', max_length=255, null=True),
        ),
    ]
